"""
Phase 3: Curated Seed Data — Major Narrators of Kutub al-Sittah
Hand-crafted biographical records for the most important Hadith narrators.
Sources: Tahdhib al-Kamal, Taqrib al-Tahdhib, Siyar A'lam al-Nubala, Wikipedia.

Run: python scripts/seed_core_rijal.py
"""

import json
import re

# ──────────────────────────────────────────────────────────────────────────────
# CORE CURATED RIJAL DATA
# Fields: id, name_en, name_ar, kunya_en, kunya, generation, tabaqat_number,
#         born_ah, died_ah, born_ce, died_ce, city_of_birth, city_of_death,
#         region, is_sahabi, is_thiqah, grade, grade_ar, hadith_count,
#         bio_en, bio_ar (short), books, sources, external_ids
# ──────────────────────────────────────────────────────────────────────────────

CORE_RIJAL = [

    # ═══════════════════════════════════════════════════════
    # GENERATION 1: SAHABAH (Companions)
    # ═══════════════════════════════════════════════════════

    {
        "id": "rawi_abu_hurairah",
        "name_en": "Abd al-Rahman ibn Sakhr al-Dawsi",
        "name_ar": "عبد الرحمن بن صخر الدوسي",
        "name_id": "Abdurrahman bin Shakhr ad-Dawsi",
        "kunya_en": "Abu Hurairah",
        "kunya": "أبو هريرة",
        "laqab_en": "The Father of the Kitten",
        "nisba_en": "al-Dawsi al-Yamani",
        "nisba": "الدوسي اليماني",
        "name_variants": ["Abu Huraira", "Abu Hureyra", "Aba Hurairah", "Abu Huraira"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -21,  # ~21 BH
        "died_ah": 57,
        "born_ce": 603,
        "died_ce": 678,
        "city_of_birth": "Al-Bahrain / Daws (Yemen)",
        "city_of_death": "Medina (Al-Aqiq)",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "grade_detail": "Most prolific narrator of Hadith. Companion of the Prophet ﷺ for ~4 years.",
        "grade_source": "ijma'",
        "hadith_count": 5374,
        "bio_en": "Abu Hurairah (رضي الله عنه) was a companion of Prophet Muhammad ﷺ and one of the most prolific narrators of Hadith. Born in the Daws tribe of Yemen, he embraced Islam in 7 AH and remained closely attached to the Prophet ﷺ. Known for his exceptional memory, he narrated 5,374 traditions recorded in the Six Books.",
        "bio_ar": "أبو هريرة الدوسي اليماني، صحابي جليل، أكثر الصحابة رواية للحديث النبوي، أسلم عام 7هـ وصحب النبي ﷺ نحو أربع سنوات.",
        "bio_id": "Abu Hurairah adalah sahabat Nabi Muhammad ﷺ yang paling banyak meriwayatkan hadits, dengan total 5.374 hadits.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {
            "tahdhib_kamal": "vol 34 p 366",
            "taqrib_tahdhib": "no. 8264",
            "siyar": "vol 2 p 578"
        },
        "external_ids": {"wikidata": "Q315436"}
    },

    {
        "id": "rawi_aisha_bint_abi_bakr",
        "name_en": "Aisha bint Abi Bakr al-Siddiq",
        "name_ar": "عائشة بنت أبي بكر الصديق",
        "name_id": "Aisyah binti Abu Bakar ash-Shiddiq",
        "kunya_en": "Umm al-Mu'minin (Mother of the Believers)",
        "kunya": "أم المؤمنين",
        "laqab_en": "al-Siddiqah (the Truthful)",
        "name_variants": ["Aisha", "'A'isha", "A'isha", "Aishah", "Ayesha"],
        "generation": "Sahabi",
        "generation_ar": "صحابية",
        "tabaqat_number": 1,
        "gender": "female",
        "born_ah": -9,
        "died_ah": 58,
        "born_ce": 614,
        "died_ce": 678,
        "city_of_birth": "Mecca",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابية",
        "grade_detail": "Wife of the Prophet ﷺ, Mother of the Believers, foremost female authority in Hadith and Fiqh.",
        "grade_source": "ijma'",
        "hadith_count": 2210,
        "bio_en": "Aisha (رضي الله عنها), daughter of Abu Bakr al-Siddiq, was the wife of Prophet Muhammad ﷺ and one of the greatest scholars of early Islam. She narrated 2,210 hadith and was a leading authority in Fiqh, Quranic commentary, and Arabic poetry.",
        "bio_ar": "عائشة بنت أبي بكر الصديق، أم المؤمنين، زوج النبي ﷺ وإحدى أكثر الصحابيات رواية للحديث.",
        "bio_id": "Aisyah binti Abu Bakar adalah istri Nabi Muhammad ﷺ dan salah satu ulama wanita terbesar dalam Islam awal.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {
            "tahdhib_kamal": "vol 35 p 227",
            "taqrib_tahdhib": "no. 8596"
        },
        "external_ids": {"wikidata": "Q242409"}
    },

    {
        "id": "rawi_ibn_umar",
        "name_en": "Abdullah ibn Umar ibn al-Khattab",
        "name_ar": "عبد الله بن عمر بن الخطاب",
        "name_id": "Abdullah bin Umar bin al-Khattab",
        "kunya_en": "Abu Abd al-Rahman",
        "kunya": "أبو عبد الرحمن",
        "name_variants": ["Ibn Umar", "Ibn 'Umar", "Abdullah bin Umar", "'Abdullah bin 'Umar"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -10,
        "died_ah": 73,
        "born_ce": 614,
        "died_ce": 693,
        "city_of_birth": "Mecca",
        "city_of_death": "Mecca",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 2630,
        "bio_en": "Abdullah ibn Umar (رضي الله عنهما), son of the second Caliph Umar ibn al-Khattab, was one of the most learned and devout companions of the Prophet ﷺ. He narrated 2,630 hadith and was renowned for his strict adherence to the Sunnah.",
        "bio_ar": "عبد الله بن عمر بن الخطاب القرشي العدوي، صحابي جليل، نجل الخليفة الثاني، من أكثر الصحابة اتباعاً للسنة.",
        "bio_id": "Abdullah bin Umar adalah sahabat Nabi ﷺ yang terkenal dengan ketaatannya terhadap Sunnah.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 3479", "siyar": "vol 3 p 203"},
        "external_ids": {"wikidata": "Q313694"}
    },

    {
        "id": "rawi_ibn_abbas",
        "name_en": "Abdullah ibn Abbas ibn Abd al-Muttalib",
        "name_ar": "عبد الله بن عباس بن عبد المطلب",
        "name_id": "Abdullah bin Abbas bin Abdil Muthallib",
        "kunya_en": "Abu al-Abbas",
        "kunya": "أبو العباس",
        "laqab_en": "Hibr al-Ummah (Scholar of the Ummah), al-Bahr (The Sea)",
        "name_variants": ["Ibn Abbas", "Ibn 'Abbas", "Abdullah bin Abbas", "'Abdullah bin 'Abbas"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -3,
        "died_ah": 68,
        "born_ce": 619,
        "died_ce": 687,
        "city_of_birth": "Mecca",
        "city_of_death": "Ta'if",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 1660,
        "bio_en": "Abdullah ibn Abbas (رضي الله عنهما), cousin of Prophet Muhammad ﷺ, was the foremost Quranic exegete (mufassir) of the early ummah. The Prophet ﷺ prayed for him: 'O Allah, give him understanding of the religion and teach him interpretation.'",
        "bio_ar": "عبد الله بن عباس بن عبد المطلب، ابن عم النبي ﷺ، أعلم الصحابة بتفسير القرآن، دعا له النبي ﷺ.",
        "bio_id": "Abdullah bin Abbas adalah sepupu Nabi ﷺ dan mufassir terkemuka di kalangan Sahabat.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 3474", "siyar": "vol 3 p 331"},
        "external_ids": {"wikidata": "Q313689"}
    },

    {
        "id": "rawi_anas_bin_malik",
        "name_en": "Anas ibn Malik al-Ansari",
        "name_ar": "أنس بن مالك الأنصاري",
        "name_id": "Anas bin Malik al-Anshari",
        "kunya_en": "Abu Hamza",
        "kunya": "أبو حمزة",
        "name_variants": ["Anas", "Anas bin Malik", "Anas ibn Malik"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -10,
        "died_ah": 93,
        "born_ce": 612,
        "died_ce": 712,
        "city_of_birth": "Medina",
        "city_of_death": "Basra",
        "region": "Iraq",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 2286,
        "bio_en": "Anas ibn Malik (رضي الله عنه) served the Prophet ﷺ for 10 years in Medina. He was among the last of the Sahabah to die and is one of the most prolific narrators. He narrated 2,286 hadith.",
        "bio_ar": "أنس بن مالك الأنصاري، خادم النبي ﷺ عشر سنوات، آخر من مات من الصحابة في البصرة.",
        "bio_id": "Anas bin Malik adalah pelayan Nabi ﷺ selama 10 tahun dan termasuk sahabat yang paling akhir wafat.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 280", "siyar": "vol 3 p 395"},
        "external_ids": {"wikidata": "Q301930"}
    },

    {
        "id": "rawi_jabir_bin_abdillah",
        "name_en": "Jabir ibn Abdullah al-Ansari",
        "name_ar": "جابر بن عبد الله الأنصاري",
        "name_id": "Jabir bin Abdullah al-Anshari",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "name_variants": ["Jabir", "Jabir bin Abdullah", "Jabir ibn 'Abdullah"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -16,
        "died_ah": 78,
        "born_ce": 607,
        "died_ce": 697,
        "city_of_birth": "Medina",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 1540,
        "bio_en": "Jabir ibn Abdullah al-Ansari (رضي الله عنه) was a renowned companion from the Ansar of Medina. He narrated 1,540 hadith and was known for his journeys to seek knowledge.",
        "bio_ar": "جابر بن عبد الله الأنصاري السلمي، صحابي جليل من الأنصار، روى 1540 حديثاً.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 870"},
        "external_ids": {"wikidata": "Q350505"}
    },

    {
        "id": "rawi_abu_said_al_khudri",
        "name_en": "Sa'd ibn Malik al-Khudri",
        "name_ar": "سعد بن مالك الخدري",
        "name_id": "Sa'd bin Malik al-Khudri",
        "kunya_en": "Abu Sa'id al-Khudri",
        "kunya": "أبو سعيد الخدري",
        "name_variants": ["Abu Sa'id", "Abu Sa'id Al-Khudri", "Abu Saeed Al-Khudri"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -13,
        "died_ah": 74,
        "born_ce": 614,
        "died_ce": 693,
        "city_of_birth": "Medina",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 1170,
        "bio_en": "Abu Sa'id al-Khudri (رضي الله عنه) was a prolific companion who participated in 12 expeditions with the Prophet ﷺ. He narrated 1,170 hadith.",
        "bio_ar": "أبو سعيد الخدري، صحابي جليل، شهد مع النبي ﷺ اثنتي عشرة غزوة.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 2273"},
        "external_ids": {"wikidata": "Q355494"}
    },

    {
        "id": "rawi_abu_musa_al_ashari",
        "name_en": "Abdullah ibn Qays al-Ash'ari",
        "name_ar": "عبد الله بن قيس الأشعري",
        "name_id": "Abdullah bin Qais al-Asy'ari",
        "kunya_en": "Abu Musa al-Ash'ari",
        "kunya": "أبو موسى الأشعري",
        "name_variants": ["Abu Musa", "Abu Musa Al-Ash`ari", "Abu Musa al-Ashari"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -21,
        "died_ah": 52,
        "born_ce": 603,
        "died_ce": 662,
        "city_of_birth": "Zabid (Yemen)",
        "city_of_death": "Kufa",
        "region": "Iraq",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 360,
        "bio_en": "Abu Musa al-Ash'ari (رضي الله عنه) was a prominent companion from Yemen who was appointed governor of Basra and Kufa by Umar ibn al-Khattab.",
        "bio_ar": "أبو موسى الأشعري، صحابي جليل من اليمن، ولاه عمر بن الخطاب البصرة والكوفة.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 3476"},
        "external_ids": {"wikidata": "Q313688"}
    },

    {
        "id": "rawi_umar_ibn_al_khattab",
        "name_en": "Umar ibn al-Khattab al-Adawi al-Qurashi",
        "name_ar": "عمر بن الخطاب العدوي القرشي",
        "name_id": "Umar bin al-Khaththab",
        "kunya_en": "Abu Hafs",
        "kunya": "أبو حفص",
        "laqab_en": "al-Faruq (The Distinguisher of Truth from Falsehood)",
        "name_variants": ["Umar", "Umar bin Al-Khattab", "'Umar", "'Umar bin Al-Khattab"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -40,
        "died_ah": 23,
        "born_ce": 584,
        "died_ce": 644,
        "city_of_birth": "Mecca",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 537,
        "bio_en": "Umar ibn al-Khattab (رضي الله عنه), the second Caliph of Islam, was among the closest companions of the Prophet ﷺ. He embraced Islam in 6 BH and was known for his justice and wisdom.",
        "bio_ar": "عمر بن الخطاب القرشي العدوي، الفاروق، ثاني الخلفاء الراشدين، أسلم في السنة السادسة قبل الهجرة.",
        "bio_id": "Umar bin al-Khaththab adalah Khalifah kedua dalam Islam, dikenal dengan keadilan dan ketegasannya.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"siyar": "vol 1 p 306"},
        "external_ids": {"wikidata": "Q178947"}
    },

    {
        "id": "rawi_ali_ibn_abi_talib",
        "name_en": "Ali ibn Abi Talib ibn Abd al-Muttalib",
        "name_ar": "علي بن أبي طالب بن عبد المطلب",
        "name_id": "Ali bin Abi Thalib",
        "kunya_en": "Abu al-Hasan",
        "kunya": "أبو الحسن",
        "laqab_en": "Amir al-Mu'minin",
        "name_variants": ["Ali", "'Ali", "Ali bin Abi Talib"],
        "generation": "Sahabi",
        "generation_ar": "صحابي",
        "tabaqat_number": 1,
        "gender": "male",
        "born_ah": -23,
        "died_ah": 40,
        "born_ce": 601,
        "died_ce": 661,
        "city_of_birth": "Mecca",
        "city_of_death": "Kufa",
        "region": "Iraq",
        "is_sahabi": True,
        "is_thiqah": True,
        "grade": "Sahabi",
        "grade_ar": "صحابي",
        "hadith_count": 536,
        "bio_en": "Ali ibn Abi Talib (رضي الله عنه), cousin and son-in-law of Prophet Muhammad ﷺ, was the fourth Caliph of Islam. He was known for his knowledge, bravery, and wisdom.",
        "bio_ar": "علي بن أبي طالب، ابن عم النبي ﷺ وزوج ابنته فاطمة، رابع الخلفاء الراشدين.",
        "bio_id": "Ali bin Abi Thalib adalah sepupu dan menantu Nabi ﷺ, Khalifah keempat dalam Islam.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"siyar": "vol 2 p 92"},
        "external_ids": {"wikidata": "Q3799"}
    },

    # ═══════════════════════════════════════════════════════
    # GENERATION 2: TABI'UN (Successors)
    # ═══════════════════════════════════════════════════════

    {
        "id": "rawi_nafi_mawla_ibn_umar",
        "name_en": "Nafi' al-Madani (Mawla of Ibn Umar)",
        "name_ar": "نافع المدني مولى ابن عمر",
        "name_id": "Nafi' al-Madani (Maula Ibnu Umar)",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "laqab_en": "Mawla (freedman) of Ibn Umar",
        "name_variants": ["Nafi`", "Nafi'", "Nafi al-Madani"],
        "generation": "Tabi'i",
        "generation_ar": "تابعي",
        "tabaqat_number": 3,
        "gender": "male",
        "born_ah": 30,
        "died_ah": 117,
        "born_ce": 650,
        "died_ce": 735,
        "city_of_birth": "Unknown",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Thiqah Thabt",
        "grade_ar": "ثقة ثبت",
        "grade_detail": "Imam Malik said: 'When I was uncertain about a hadith I would ask Nafi' and he would dissipate the uncertainty.' One of the most reliable transmitters.",
        "grade_source": "Ibn Hajar",
        "hadith_count": 0,
        "bio_en": "Nafi' al-Madani was the freedman (mawla) of Abdullah ibn Umar and a leading Tabi'i scholar. He transmitted a huge portion of Ibn Umar's hadith to the next generation. The chain Malik → Nafi' → Ibn Umar is known as the 'Golden Isnad' (Silsilat al-Dhahab).",
        "bio_ar": "نافع المدني، مولى عبد الله بن عمر، من كبار التابعين، ثقة ثبت. سنده عن ابن عمر تُعدّ من أصح الأسانيد.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"tahdhib_kamal": "vol 29 p 298", "taqrib_tahdhib": "no. 7117"},
        "external_ids": {"wikidata": "Q376047"}
    },

    {
        "id": "rawi_ibn_shihab_al_zuhri",
        "name_en": "Muhammad ibn Muslim ibn Ubaydullah al-Zuhri",
        "name_ar": "محمد بن مسلم بن عبيد الله الزهري",
        "name_id": "Muhammad bin Muslim bin Ubaidillah az-Zuhri",
        "kunya_en": "Abu Bakr ibn Shihab al-Zuhri",
        "kunya": "أبو بكر ابن شهاب الزهري",
        "laqab_en": "Ibn Shihab",
        "nisba_en": "al-Zuhri",
        "name_variants": ["Az-Zuhri", "Ibn Shihab", "al-Zuhri", "Ibn Shihab al-Zuhri"],
        "generation": "Tabi'i",
        "generation_ar": "تابعي",
        "tabaqat_number": 4,
        "gender": "male",
        "born_ah": 50,
        "died_ah": 124,
        "born_ce": 670,
        "died_ce": 742,
        "city_of_birth": "Medina",
        "city_of_death": "Shagab (near Ramla, Palestine)",
        "region": "Hijaz / Sham",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Thiqah Mutqin Faqih Hafidh",
        "grade_ar": "ثقة متقن فقيه حافظ",
        "grade_detail": "One of the greatest scholars of his era. Often called the first systematic compiler of Hadith. Al-Layth ibn Sa'd: 'I never saw a scholar more complete than Ibn Shihab al-Zuhri.'",
        "grade_source": "Ibn Hajar",
        "hadith_count": 0,
        "bio_en": "Ibn Shihab al-Zuhri (died 124 AH) was the foremost Tabi'i Hadith scholar. He studied under many companions including Anas ibn Malik and Sahl ibn Sa'd. Caliph Umar ibn Abd al-Aziz instructed him to compile the Hadith.",
        "bio_ar": "ابن شهاب الزهري القرشي المدني، إمام التابعين في الحديث والفقه، أحد أئمة الإسلام، توفي سنة 124هـ.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"tahdhib_kamal": "vol 26 p 419", "taqrib_tahdhib": "no. 6296", "siyar": "vol 5 p 326"},
        "external_ids": {"wikidata": "Q368296"}
    },

    {
        "id": "rawi_urwah_ibn_zubayr",
        "name_en": "Urwah ibn al-Zubayr ibn al-Awwam",
        "name_ar": "عروة بن الزبير بن العوام",
        "name_id": "Urwah bin az-Zubair bin al-Awwam",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "name_variants": ["'Urwa", "Urwa", "'Urwa bin Az-Zubair", "Urwa ibn al-Zubayr"],
        "generation": "Tabi'i",
        "generation_ar": "تابعي",
        "tabaqat_number": 3,
        "gender": "male",
        "born_ah": 23,
        "died_ah": 94,
        "born_ce": 644,
        "died_ce": 713,
        "city_of_birth": "Medina",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Thiqah",
        "grade_ar": "ثقة",
        "grade_source": "Ibn Hajar",
        "hadith_count": 0,
        "bio_en": "Urwah ibn al-Zubayr was a leading Tabi'i scholar, nephew of Aisha (رضي الله عنها). He was one of the Seven Fuqaha of Medina and is a key transmitter of Aisha's narrations.",
        "bio_ar": "عروة بن الزبير بن العوام، من فقهاء المدينة السبعة، ابن أخت السيدة عائشة.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 4574"},
        "external_ids": {"wikidata": "Q370295"}
    },

    # ═══════════════════════════════════════════════════════
    # GENERATION 3: TABI' AL-TABI'IN
    # ═══════════════════════════════════════════════════════

    {
        "id": "rawi_malik_ibn_anas",
        "name_en": "Malik ibn Anas ibn Malik al-Asbahi",
        "name_ar": "مالك بن أنس بن مالك الأصبحي",
        "name_id": "Malik bin Anas bin Malik al-Ashbahi",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "laqab_en": "Imam al-Dar (Imam of the Abode of Hijra), Imam of the Malikiyya",
        "name_variants": ["Malik", "Imam Malik", "Malik ibn Anas"],
        "generation": "Tabi' al-Tabi'in",
        "generation_ar": "تابع التابعين",
        "tabaqat_number": 7,
        "gender": "male",
        "born_ah": 93,
        "died_ah": 179,
        "born_ce": 711,
        "died_ce": 795,
        "city_of_birth": "Medina",
        "city_of_death": "Medina",
        "region": "Hijaz",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "Imam of the Malikiyya school of fiqh. His Muwatta' is one of the earliest Hadith collections. Chain: Malik → Nafi' → Ibn Umar is called 'Silsilat al-Dhahab' (Golden Chain).",
        "grade_source": "ijma' al-ulama",
        "hadith_count": 0,
        "bio_en": "Imam Malik ibn Anas (93–179 AH) was the founder of the Maliki school of Islamic law and one of the greatest hadith scholars. His al-Muwatta' is considered one of the earliest and most authentic collections of hadith.",
        "bio_ar": "مالك بن أنس الأصبحي المدني، إمام دار الهجرة، مؤسس المذهب المالكي، صاحب الموطأ، إمام جليل.",
        "bio_id": "Imam Malik bin Anas adalah pendiri mazhab Maliki dan salah satu ulama hadits terbesar dalam Islam.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"tahdhib_kamal": "vol 27 p 91", "siyar": "vol 8 p 48"},
        "external_ids": {"wikidata": "Q191996"}
    },

    {
        "id": "rawi_sufyan_al_thawri",
        "name_en": "Sufyan ibn Sa'id al-Thawri al-Kufi",
        "name_ar": "سفيان بن سعيد الثوري الكوفي",
        "name_id": "Sufyan bin Sa'id ats-Tsauri al-Kufi",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "name_variants": ["Sufyan al-Thawri", "Sufyan ath-Thawri"],
        "generation": "Tabi' al-Tabi'in",
        "generation_ar": "تابع التابعين",
        "tabaqat_number": 7,
        "gender": "male",
        "born_ah": 97,
        "died_ah": 161,
        "born_ce": 716,
        "died_ce": 778,
        "city_of_birth": "Kufa",
        "city_of_death": "Basra",
        "region": "Iraq",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Thiqah Hafidh Faqih Imam",
        "grade_ar": "ثقة حافظ فقيه إمام",
        "grade_detail": "Called 'Amir al-Mu'minin fi al-Hadith' (Commander of the Faithful in Hadith). Ibn al-Mubarak said he is like an ocean.",
        "grade_source": "Ibn Hajar (Taqrib no. 2445)",
        "hadith_count": 0,
        "bio_en": "Sufyan al-Thawri (97–161 AH) was a major Tabi' al-Tabi'in scholar known as 'Amir al-Mu'minin fi al-Hadith' for his mastery of Hadith sciences.",
        "bio_ar": "سفيان بن سعيد الثوري الكوفي، أمير المؤمنين في الحديث، إمام حافظ فقيه.",
        "books": ["bukhari", "muslim", "abudawud", "tirmidhi", "nasai", "ibnmajah"],
        "sources": {"taqrib_tahdhib": "no. 2445", "siyar": "vol 7 p 229"},
        "external_ids": {"wikidata": "Q362152"}
    },

    # ═══════════════════════════════════════════════════════
    # GENERATION 4: THE SIX COLLECTORS (أصحاب الكتب الستة)
    # ═══════════════════════════════════════════════════════

    {
        "id": "rawi_al_bukhari",
        "name_en": "Muhammad ibn Ismail al-Bukhari",
        "name_ar": "محمد بن إسماعيل البخاري",
        "name_id": "Muhammad bin Ismail al-Bukhari",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "laqab_en": "Imam of Hadith, Amir al-Mu'minin fi al-Hadith",
        "name_variants": ["Imam Bukhari", "al-Bukhari", "Bukhari"],
        "generation": "Collector",
        "generation_ar": "محدث جامع",
        "tabaqat_number": 10,
        "gender": "male",
        "born_ah": 194,
        "died_ah": 256,
        "born_ce": 810,
        "died_ce": 870,
        "city_of_birth": "Bukhara (Khorasan)",
        "city_of_death": "Khartank (near Samarkand)",
        "region": "Khorasan",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "Compiler of the Sahih al-Bukhari, considered the most authentic book after the Quran. He memorized 600,000 hadith with chains.",
        "grade_source": "ijma' al-ulama",
        "hadith_count": 0,
        "bio_en": "Imam Muhammad ibn Ismail al-Bukhari (194–256 AH) compiled al-Jami' al-Sahih, known as Sahih al-Bukhari — the most rigorously authenticated collection of Hadith. He selected 7,275 hadith from over 600,000 he examined over 16 years.",
        "bio_ar": "محمد بن إسماعيل البخاري، إمام المحدثين، صاحب الجامع الصحيح، أصح كتاب بعد القرآن الكريم.",
        "bio_id": "Imam al-Bukhari adalah penyusun Shahih al-Bukhari, koleksi hadits paling otentik yang pernah dikumpulkan.",
        "books": ["bukhari"],
        "sources": {"siyar": "vol 12 p 391"},
        "external_ids": {"wikidata": "Q334522"}
    },

    {
        "id": "rawi_muslim_ibn_hajjaj",
        "name_en": "Muslim ibn al-Hajjaj al-Qushayri al-Nishaburi",
        "name_ar": "مسلم بن الحجاج القشيري النيسابوري",
        "name_id": "Muslim bin al-Hajjaj al-Qusyairi an-Nisaburi",
        "kunya_en": "Abu al-Husayn",
        "kunya": "أبو الحسين",
        "name_variants": ["Imam Muslim", "Muslim ibn al-Hajjaj"],
        "generation": "Collector",
        "generation_ar": "محدث جامع",
        "tabaqat_number": 10,
        "gender": "male",
        "born_ah": 204,
        "died_ah": 261,
        "born_ce": 820,
        "died_ce": 875,
        "city_of_birth": "Nishapur (Khorasan)",
        "city_of_death": "Nishapur",
        "region": "Khorasan",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "Compiler of Sahih Muslim, second most authentic hadith collection. He is noted for his superior organization and methodology.",
        "grade_source": "ijma' al-ulama",
        "hadith_count": 0,
        "bio_en": "Imam Muslim ibn al-Hajjaj (204–261 AH) compiled Sahih Muslim, the second most authoritative hadith collection after Sahih al-Bukhari. He selected 7,500 hadiths from 300,000 he examined.",
        "bio_ar": "مسلم بن الحجاج النيسابوري، صاحب الصحيح، ثاني الصحيحين في الصحة والشهرة.",
        "bio_id": "Imam Muslim bin al-Hajjaj adalah penyusun Shahih Muslim, koleksi hadits terpercaya kedua setelah Shahih al-Bukhari.",
        "books": ["muslim"],
        "sources": {"siyar": "vol 12 p 557"},
        "external_ids": {"wikidata": "Q336763"}
    },

    {
        "id": "rawi_abu_dawud",
        "name_en": "Sulayman ibn al-Ash'ath al-Azdi al-Sijistani",
        "name_ar": "سليمان بن الأشعث الأزدي السجستاني",
        "name_id": "Sulaiman bin al-Asy'ats al-Azdi as-Sijistani",
        "kunya_en": "Abu Dawud",
        "kunya": "أبو داود",
        "name_variants": ["Abu Dawud", "Abu Dawood", "Abu Da'ud"],
        "generation": "Collector",
        "generation_ar": "محدث جامع",
        "tabaqat_number": 10,
        "gender": "male",
        "born_ah": 202,
        "died_ah": 275,
        "born_ce": 817,
        "died_ce": 889,
        "city_of_birth": "Sijistan (Khorasan)",
        "city_of_death": "Basra",
        "region": "Iraq",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "Compiler of Sunan Abu Dawud. He selected 4,800 from 500,000 hadiths. His collection is particularly valued in Fiqh.",
        "grade_source": "ijma' al-ulama",
        "hadith_count": 0,
        "bio_en": "Abu Dawud (202–275 AH) compiled Sunan Abu Dawud, one of the Six Canonical collections. He selected 4,800 hadith from 500,000 he gathered.",
        "bio_ar": "أبو داود السجستاني، صاحب السنن، من أئمة الحديث والفقه.",
        "bio_id": "Abu Dawud adalah penyusun Sunan Abu Dawud, salah satu dari enam kitab hadits utama.",
        "books": ["abudawud"],
        "sources": {"siyar": "vol 13 p 203"},
        "external_ids": {"wikidata": "Q349968"}
    },

    {
        "id": "rawi_al_tirmidhi",
        "name_en": "Muhammad ibn Isa al-Tirmidhi",
        "name_ar": "محمد بن عيسى الترمذي",
        "name_id": "Muhammad bin Isa at-Tirmidzi",
        "kunya_en": "Abu Isa",
        "kunya": "أبو عيسى",
        "name_variants": ["Tirmidhi", "al-Tirmidhi", "Imam Tirmidhi"],
        "generation": "Collector",
        "generation_ar": "محدث جامع",
        "tabaqat_number": 10,
        "gender": "male",
        "born_ah": 209,
        "died_ah": 279,
        "born_ce": 824,
        "died_ce": 892,
        "city_of_birth": "Tirmidh (Khorasan)",
        "city_of_death": "Tirmidh",
        "region": "Khorasan",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "hadith_count": 0,
        "bio_en": "Imam al-Tirmidhi (209–279 AH) compiled the Jami' al-Tirmidhi (also known as Sunan al-Tirmidhi), notable for its unique grading of each hadith's authenticity level.",
        "bio_ar": "محمد بن عيسى الترمذي، صاحب الجامع الكبير، من أئمة الحديث.",
        "bio_id": "Imam at-Tirmidzi adalah penyusun Jami' at-Tirmidzi, yang unik karena mencantumkan derajat setiap hadits.",
        "books": ["tirmidhi"],
        "sources": {"siyar": "vol 13 p 270"},
        "external_ids": {"wikidata": "Q312782"}
    },

    {
        "id": "rawi_al_nasai",
        "name_en": "Ahmad ibn Shu'ayb al-Nasa'i",
        "name_ar": "أحمد بن شعيب النسائي",
        "name_id": "Ahmad bin Syu'aib an-Nasa'i",
        "kunya_en": "Abu Abd al-Rahman",
        "kunya": "أبو عبد الرحمن",
        "name_variants": ["al-Nasa'i", "al-Nasai", "Imam al-Nasai"],
        "generation": "Collector",
        "generation_ar": "محدث جامع",
        "tabaqat_number": 10,
        "gender": "male",
        "born_ah": 215,
        "died_ah": 303,
        "born_ce": 829,
        "died_ce": 915,
        "city_of_birth": "Nasa (Khorasan)",
        "city_of_death": "Mecca / Ramla",
        "region": "Khorasan",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "His Sunan al-Nasa'i is considered the most critically rigorous of the four Sunan collections in terms of narrator criticism.",
        "hadith_count": 0,
        "bio_en": "Imam al-Nasa'i (215–303 AH) compiled the Sunan al-Nasa'i, known for its strict conditions in accepting narrators. He is called 'the most critical in narrator evaluation among the Six.'",
        "bio_ar": "أحمد بن شعيب النسائي، صاحب السنن الصغرى والكبرى، من أشد المحدثين في الجرح والتعديل.",
        "bio_id": "Imam an-Nasa'i adalah penyusun Sunan an-Nasa'i yang terkenal dengan ketelitian dalam menilai para perawi.",
        "books": ["nasai"],
        "sources": {"siyar": "vol 14 p 125"},
        "external_ids": {"wikidata": "Q346890"}
    },

    {
        "id": "rawi_ibn_majah",
        "name_en": "Muhammad ibn Yazid ibn Majah al-Qazwini",
        "name_ar": "محمد بن يزيد بن ماجه القزويني",
        "name_id": "Muhammad bin Yazid bin Majah al-Qazwini",
        "kunya_en": "Abu Abdullah",
        "kunya": "أبو عبد الله",
        "name_variants": ["Ibn Majah", "Ibn Maajah"],
        "generation": "Collector",
        "generation_ar": "محدث جامع",
        "tabaqat_number": 10,
        "gender": "male",
        "born_ah": 209,
        "died_ah": 273,
        "born_ce": 824,
        "died_ce": 887,
        "city_of_birth": "Qazwin (Persia)",
        "city_of_death": "Qazwin",
        "region": "Khorasan",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh",
        "grade_ar": "إمام حافظ",
        "hadith_count": 0,
        "bio_en": "Imam Ibn Majah (209–273 AH) compiled the Sunan Ibn Majah, the sixth canonical Hadith collection. He also compiled a Tafsir and a History. His Sunan contains 4,341 hadith.",
        "bio_ar": "محمد بن يزيد بن ماجه القزويني، صاحب السنن، من أئمة الحديث والتفسير والتاريخ.",
        "bio_id": "Imam Ibnu Majah adalah penyusun Sunan Ibnu Majah, kitab hadits kanonik keenam dalam Islam.",
        "books": ["ibnmajah"],
        "sources": {"siyar": "vol 13 p 277"},
        "external_ids": {"wikidata": "Q347440"}
    },

    # ═══════════════════════════════════════════════════════
    # EVALUATORS (Classical Rijal Critics)
    # ═══════════════════════════════════════════════════════

    {
        "id": "rawi_ibn_hajar_al_asqalani",
        "name_en": "Ahmad ibn Ali ibn Hajar al-Asqalani",
        "name_ar": "أحمد بن علي بن حجر العسقلاني",
        "name_id": "Ahmad bin Ali bin Hajar al-Asqalani",
        "kunya_en": "Abu al-Fadl Shihab al-Din",
        "kunya": "أبو الفضل شهاب الدين",
        "laqab_en": "Amir al-Mu'minin fi al-Hadith (later era)",
        "name_variants": ["Ibn Hajar", "Ibn Hajar al-Asqalani", "Al-Asqalani"],
        "generation": "Later Scholar",
        "generation_ar": "عالم متأخر",
        "tabaqat_number": 12,
        "gender": "male",
        "born_ah": 773,
        "died_ah": 852,
        "born_ce": 1372,
        "died_ce": 1449,
        "city_of_birth": "Cairo",
        "city_of_death": "Cairo",
        "region": "Egypt",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "Author of Fath al-Bari (commentary on Sahih al-Bukhari), Taqrib al-Tahdhib (narrator grades), Tahdhib al-Tahdhib, Lisan al-Mizan.",
        "hadith_count": 0,
        "bio_en": "Ibn Hajar al-Asqalani (773–852 AH) was the foremost hadith scholar of the 9th century AH. His Fath al-Bari is the most celebrated commentary on Sahih al-Bukhari, and his Taqrib al-Tahdhib provides the definitive grading for each narrator in the Kutub al-Sittah.",
        "bio_ar": "أحمد بن علي بن حجر العسقلاني، شيخ الإسلام، حافظ عصره، صاحب فتح الباري وتقريب التهذيب.",
        "bio_id": "Ibnu Hajar al-Asqalani adalah ulama hadits terbesar abad ke-9 Hijriyah, penyusun Fath al-Bari dan Taqrib at-Tahdzib.",
        "books": [],
        "sources": {"siyar": "vol 22 p 1"},
        "external_ids": {"wikidata": "Q356816"}
    },

    {
        "id": "rawi_al_dhahabi",
        "name_en": "Shams al-Din Muhammad ibn Ahmad al-Dhahabi",
        "name_ar": "شمس الدين محمد بن أحمد الذهبي",
        "name_id": "Syamsuddin Muhammad bin Ahmad adz-Dzahabi",
        "kunya_en": "Abu Abdullah Shams al-Din",
        "kunya": "أبو عبد الله شمس الدين",
        "name_variants": ["al-Dhahabi", "al-Zahabi", "Imam al-Dhahabi"],
        "generation": "Later Scholar",
        "generation_ar": "عالم متأخر",
        "tabaqat_number": 12,
        "gender": "male",
        "born_ah": 673,
        "died_ah": 748,
        "born_ce": 1274,
        "died_ce": 1348,
        "city_of_birth": "Damascus",
        "city_of_death": "Damascus",
        "region": "Sham",
        "is_sahabi": False,
        "is_thiqah": True,
        "grade": "Imam Hafidh Hujjah",
        "grade_ar": "إمام حافظ حجة",
        "grade_detail": "Author of Mizan al-I'tidal (narrator criticism), Siyar A'lam al-Nubala (biographies of major scholars), Tadhkirat al-Huffaz.",
        "hadith_count": 0,
        "bio_en": "Al-Dhahabi (673–748 AH) was a great historian and hadith scholar. His encyclopedic works — Siyar A'lam al-Nubala, Mizan al-I'tidal, and Tadhkirat al-Huffaz — are essential references in Islamic biography.",
        "bio_ar": "شمس الدين الذهبي الدمشقي، محدث حافظ مؤرخ، صاحب سير أعلام النبلاء وميزان الاعتدال.",
        "bio_id": "Imam adz-Dzahabi adalah sejarawan dan ahli hadits besar, penyusun Siyar A'lam an-Nubala.",
        "books": [],
        "sources": {},
        "external_ids": {"wikidata": "Q324859"}
    },
]


def main():
    print(f"Core Rijal records: {len(CORE_RIJAL)}")

    # Validate all have required fields
    for r in CORE_RIJAL:
        assert r.get("id"), f"Missing id in: {r}"
        assert r.get("name_en"), f"Missing name_en in: {r}"
        assert r.get("name_ar"), f"Missing name_ar in: {r}"
        assert r.get("generation"), f"Missing generation in: {r}"

    # Save
    with open("scratch/rijal_core_seed.json", "w", encoding="utf-8") as f:
        json.dump(CORE_RIJAL, f, ensure_ascii=False, indent=2)

    # Summary
    gens = {}
    for r in CORE_RIJAL:
        g = r["generation"]
        gens[g] = gens.get(g, 0) + 1

    print("\nBreakdown by generation:")
    for g, count in sorted(gens.items()):
        print(f"  {g}: {count}")

    print(f"\n✅ Saved to scratch/rijal_core_seed.json")


if __name__ == "__main__":
    main()
